version: '3.8'

services:
   nginx:
     image: nginx
     volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf
       - ./conf/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
       - ./conf/self-signed.conf:/etc/nginx/snippets/self-signed.conf
       - ./conf/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
       - ./conf/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
       - ./conf/default.conf:/etc/nginx/conf.d/default.conf
       - ./conf/dhparam.pem:/etc/ssl/certs/dhparam.pem
     container_name: nginx
     restart: always
     ports:
       - "80:80"
   es:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
     container_name: es
     ports: 
      - 2345:9200
     environment: 
      - discovery.type=single-node

