version: '3.8'

services:
   oauth_server:
     image: server:latest
     container_name: OAuth.Server
     environment: 
      - DOMAIN=host.docker.internal
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/aspnetapp.pfx
      
     volumes: 
      - ./aspnetapp.pfx:/etc/ssl/aspnetapp.pfx
     ports:
      - 49001:443
      - 49000:80

   resource_api:
    image: api:latest
    container_name: ResourceApi
    environment: 
      - DOMAIN=host.docker.internal
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/aspnetapp.pfx
      
    volumes: 
      - ./aspnetapp.pfx:/etc/ssl/aspnetapp.pfx
    ports:
      - 49003:443
      - 49002:80
